In [191]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import Imputer

In [192]:
df = pd.read_pickle('final_data_with_features_attributes.pkl')
df.head()

,alias,categories,coordinates.latitude,coordinates.longitude,hours,id,is_closed,location.display_address,location.zip_code,name,...,RestaurantsDelivery,RestaurantsGoodForGroups,RestaurantsPriceRange2,RestaurantsReservations,RestaurantsTableService,RestaurantsTakeOut,Smoking,WheelchairAccessible,WiFi,cuisine_y
0,jersey-mikes-subs-gilbert-2,"[{'alias': 'sandwiches', 'title': 'Sandwiches'...",33.378695,-111.812692,"[{'open': [{'is_overnight': False, 'start': '1...",sVHAdRWYLXlnsNw2TsdwxQ,True,"[891 E Baseline Rd, Ste 102, Gilbert, AZ 85233]",85233,Jersey Mike's Subs,...,False,True,1.0,False,False,True,NaN,NaN,no,hotdogs
1,sauce-pizza-and-wine-scottsdale-2,"[{'alias': 'italian', 'title': 'Italian'}, {'a...",33.617460,-111.926260,"[{'open': [{'is_overnight': False, 'start': '1...",4LB4xtFAwfvJRachr6Eaxw,False,"[14418 N Scottsdale Rd, Ste 181, Scottsdale, A...",85254,Sauce Pizza and Wine,...,True,True,2.0,False,False,True,NaN,True,no,italian
2,fuddruckers-phoenix-3,"[{'alias': 'burgers', 'title': 'Burgers'}, {'a...",33.566990,-112.116241,NaN,hI_WID6sP7EOgPeFFJPPwQ,False,"[8941 North Black Canyon Hwy, Phoenix, AZ 85021]",85021,Fuddruckers,...,False,True,2.0,False,False,True,NaN,NaN,free,tradamerican
3,peter-piper-pizza-scottsdale-4,"[{'alias': 'pizza', 'title': 'Pizza'}, {'alias...",33.464893,-111.916801,"[{'open': [{'is_overnight': False, 'start': '1...",PWifWVSyaaQpSgRimHviWQ,False,"[7607 E McDowell Rd, Ste 101, Scottsdale, AZ 8...",85257,Peter Piper Pizza,...,False,True,2.0,True,False,True,NaN,True,free,pizza
4,five-guys-scottsdale,"[{'alias': 'burgers', 'title': 'Burgers'}, {'a...",33.626620,-111.925025,"[{'open': [{'is_overnight': False, 'start': '1...",rxjHvIvV_BlzKa8ftRUpGA,False,"[15435 Scottsdale Rd, Scottsdale, AZ 85260]",85260,Five Guys,...,False,True,1.0,False,False,True,NaN,True,no,hotdogs

In [193]:
df.columns

Index(['alias', 'categories', 'coordinates.latitude', 'coordinates.longitude',
       'hours', 'id', 'is_closed', 'location.display_address',
       'location.zip_code', 'name', 'price', 'rating', 'review_count',
       '0.5m_count', '0.5m_count_similar', '1m_count', '1m_count_similar',
       '2m_count', '2m_count_similar', '3m_count', '3m_count_similar',
       'is_fastfood', 'cuisine_x', 'price_ordinal', 'income', 'is_chain',
       'AcceptsInsurance', 'AgesAllowed', 'Alcohol', 'Ambience.casual',
       'Ambience.classy', 'Ambience.divey', 'Ambience.hipster',
       'Ambience.intimate', 'Ambience.romantic', 'Ambience.touristy',
       'Ambience.trendy', 'Ambience.upscale', 'BYOB', 'BYOBCorkage',
       'BestNights.friday', 'BestNights.monday', 'BestNights.saturday',
       'BestNights.sunday', 'BestNights.thursday', 'BestNights.tuesday',
       'BestNights.wednesday', 'BikeParking', 'BusinessAcceptsBitcoin',
       'BusinessAcceptsCreditCards', 'BusinessParking.garage',
       'BusinessParking.lot', 'BusinessParking.street',
       'BusinessParking.valet', 'BusinessParking.validated',
       'ByAppointmentOnly', 'Caters', 'CoatCheck', 'Corkage',
       'DietaryRestrictions.dairy-free', 'DietaryRestrictions.gluten-free',
       'DietaryRestrictions.halal', 'DietaryRestrictions.kosher',
       'DietaryRestrictions.soy-free', 'DietaryRestrictions.vegan',
       'DietaryRestrictions.vegetarian', 'DogsAllowed', 'DriveThru',
       'GoodForDancing', 'GoodForKids', 'GoodForMeal.breakfast',
       'GoodForMeal.brunch', 'GoodForMeal.dessert', 'GoodForMeal.dinner',
       'GoodForMeal.latenight', 'GoodForMeal.lunch', 'HappyHour', 'HasTV',
       'Music.background_music', 'Music.dj', 'Music.jukebox', 'Music.karaoke',
       'Music.live', 'Music.no_music', 'Music.video', 'NoiseLevel',
       'Open24Hours', 'OutdoorSeating', 'RestaurantsAttire',
       'RestaurantsCounterService', 'RestaurantsDelivery',
       'RestaurantsGoodForGroups', 'RestaurantsPriceRange2',
       'RestaurantsReservations', 'RestaurantsTableService',
       'RestaurantsTakeOut', 'Smoking', 'WheelchairAccessible', 'WiFi',
       'cuisine_y'],
      dtype='object')

In [194]:
y_columns = 'is_closed'
x_columns = ['rating', 'review_count',
       '0.5m_count', '0.5m_count_similar', '1m_count', '1m_count_similar',
       '2m_count', '2m_count_similar', '3m_count', '3m_count_similar',
       'is_fastfood', 'price_ordinal', 'income', 'is_chain',
       'AcceptsInsurance', 'AgesAllowed', 'Alcohol', 'Ambience.casual',
       'Ambience.classy', 'Ambience.divey', 'Ambience.hipster',
       'Ambience.intimate', 'Ambience.romantic', 'Ambience.touristy',
       'Ambience.trendy', 'Ambience.upscale', 'BYOB', 'BYOBCorkage',
       'BestNights.friday', 'BestNights.monday', 'BestNights.saturday',
       'BestNights.sunday', 'BestNights.thursday', 'BestNights.tuesday',
       'BestNights.wednesday', 'BikeParking', 'BusinessAcceptsBitcoin',
       'BusinessAcceptsCreditCards', 'BusinessParking.garage',
       'BusinessParking.lot', 'BusinessParking.street',
       'BusinessParking.valet', 'BusinessParking.validated',
       'ByAppointmentOnly', 'Caters', 'CoatCheck', 'Corkage',
       'DietaryRestrictions.dairy-free', 'DietaryRestrictions.gluten-free',
       'DietaryRestrictions.halal', 'DietaryRestrictions.kosher',
       'DietaryRestrictions.soy-free', 'DietaryRestrictions.vegan',
       'DietaryRestrictions.vegetarian', 'DogsAllowed', 'DriveThru',
       'GoodForDancing', 'GoodForKids', 'GoodForMeal.breakfast',
       'GoodForMeal.brunch', 'GoodForMeal.dessert', 'GoodForMeal.dinner',
       'GoodForMeal.latenight', 'GoodForMeal.lunch', 'HappyHour', 'HasTV',
       'Music.background_music', 'Music.dj', 'Music.jukebox', 'Music.karaoke',
       'Music.live', 'Music.no_music', 'Music.video', 'NoiseLevel',
       'Open24Hours', 'OutdoorSeating', 'RestaurantsAttire',
       'RestaurantsCounterService', 'RestaurantsDelivery',
       'RestaurantsGoodForGroups', 'RestaurantsPriceRange2',
       'RestaurantsReservations', 'RestaurantsTableService',
       'RestaurantsTakeOut', 
       'Smoking', 
       'WheelchairAccessible', 
       'WiFi',
       'cuisine_y']

In [195]:
x_df = df[x_columns].copy()

In [196]:
x_df.head()

,rating,review_count,0.5m_count,0.5m_count_similar,1m_count,1m_count_similar,2m_count,2m_count_similar,3m_count,3m_count_similar,...,RestaurantsDelivery,RestaurantsGoodForGroups,RestaurantsPriceRange2,RestaurantsReservations,RestaurantsTableService,RestaurantsTakeOut,Smoking,WheelchairAccessible,WiFi,cuisine_y
0,3.0,29.0,12,8,18,10,55,25,112,36,...,False,True,1.0,False,False,True,NaN,NaN,no,hotdogs
1,3.5,182.0,21,9,44,13,98,23,167,35,...,True,True,2.0,False,False,True,NaN,True,no,italian
2,3.5,99.0,5,3,30,11,80,24,136,34,...,False,True,2.0,False,False,True,NaN,NaN,free,tradamerican
3,3.0,21.0,9,5,32,10,83,16,241,30,...,False,True,2.0,True,False,True,NaN,True,free,pizza
4,3.5,109.0,26,4,59,9,112,23,148,36,...,False,True,1.0,False,False,True,NaN,True,no,hotdogs

In [197]:
x_df_objects = x_df.select_dtypes(include=['object'])

In [198]:
for name in x_df_objects.head():
    x_df[name] = x_df[name].astype('category')
    nancount = x_df[name].isnull().sum()
    if nancount > 0.2*len(x_df[name]):
#         print("deleting", name)
        del x_df[name]
    else:
#         print(name)
        codes = x_df[name].cat.codes
        counts = codes.value_counts().sort_index(ascending=False)
        try:
            minus_ones = counts[-1]
        except KeyError:
            x_df[name] = codes
            continue
#         print(counts)
        counts_sum = counts[:-1].sum()
        counts_percent = counts[:-1]/counts_sum
#         print(counts_percent)
        index = 0
        minus_one_codes = codes.loc[codes == -1]
        for idx, percent in counts_percent.iteritems():
#             print(idx, percent)
            c = int(np.round(minus_ones*percent))
            minus_one_codes[index:index+c] = idx
            index += c
        codes[codes == -1] = minus_one_codes
#         print("==========")
#         print(codes.value_counts())
#         print("==========")
        x_df[name] = codes

In [199]:
x_df['RestaurantsPriceRange2'] = x_df['RestaurantsPriceRange2'].fillna(0)

In [200]:
y = df[y_columns].astype(int)

In [201]:
x = x_df
x.head()

,rating,review_count,0.5m_count,0.5m_count_similar,1m_count,1m_count_similar,2m_count,2m_count_similar,3m_count,3m_count_similar,...,OutdoorSeating,RestaurantsAttire,RestaurantsDelivery,RestaurantsGoodForGroups,RestaurantsPriceRange2,RestaurantsReservations,RestaurantsTableService,RestaurantsTakeOut,WiFi,cuisine_y
0,3.0,29.0,12,8,18,10,55,25,112,36,...,1,0,0,1,1.0,0,0,1,1,22
1,3.5,182.0,21,9,44,13,98,23,167,35,...,1,0,1,1,2.0,0,0,1,1,25
2,3.5,99.0,5,3,30,11,80,24,136,34,...,0,0,0,1,2.0,0,0,1,0,49
3,3.0,21.0,9,5,32,10,83,16,241,30,...,1,0,0,1,2.0,1,0,1,0,40
4,3.5,109.0,26,4,59,9,112,23,148,36,...,1,0,0,1,1.0,0,0,1,1,22

In [202]:
x.to_pickle("x.pkl")
y.to_pickle("y.pkl")